import 'package:flutter/material.dart';
import 'package:shoppingapp/product%20details/models.dart';
List<Products> ExclusiveOfferList = [
  Products(
      id: 1,
      title: 'Apple',
      subtitle: 'Fruit',
      amount: '1.3',
      quantity: 1,
      imageURL: 'images/a.jpg'),
  Products(
      id: 2,
      title: 'Banana',
      subtitle: 'Fruits',
      amount: '1.0',
      quantity: 1,
      imageURL: 'images/b.jpg'),
  Products(
      id: 3,
      title: 'Grapes',
      subtitle: 'Fruits',
      amount: '2.0',
      quantity: 1,
      imageURL: 'images/g.jpg'),
  Products(
      id: 4,
      title: 'JackFruits',
      subtitle: 'Fruits',
      amount: '0.5',
      quantity: 1,
      imageURL: 'images/j.jpg'),
  Products(
      id: 5,
      title: 'Blue Berry',
      subtitle: 'Fruits',
      amount: '2.5',
      quantity: 1,
      imageURL: 'images/bb.jpeg'),
  Products(
      id: 6,
      title: 'StrawBerry',
      subtitle: 'Fruits',
      amount: '1.6',
      quantity: 1,
      imageURL: 'images/s.jpg'),
];

  List<Products> BestSellingList = [
    Products(
      id: 7,
        title: 'Pepsi',
        subtitle: 'Fruit',
        amount: '25',
        quantity: 1,
        imageURL: 'images/p.jpg'),
    Products(
      id: 8,
        title: 'Coco-Cola',
        subtitle: 'Fruits',
        amount: '25',
        quantity: 1,
        imageURL: 'images/c.jpg'),
    Products(
      id: 9,
        title: 'Amul Butter',
        subtitle: 'Fruits',
        amount: '30',
        quantity: 1,
        imageURL: 'images/ab.png'),
    Products(
      id: 10,
        title: 'Horlicks',
        subtitle: 'Fruits',
        amount: '50',
        quantity: 1,
        imageURL: 'images/h.jpeg'),
    Products(
      id: 11,
        title: 'Blue Berry',
        subtitle: 'Fruits',
        amount: '2.5',
        quantity: 1,
        imageURL: 'images/bb.jpeg'),
    Products(
      id: 12,
        title: 'Oliv Oli',
        subtitle: 'Fruits',
        amount: '59',
        quantity: 1,
        imageURL: 'images/o.jpeg'),
  ];
  List<Products> Rice = [];

  List<GroceryItems> Item = [
    GroceryItems(
        title: 'Pulses',
        itemColor: Colors.pink.shade300,
        imageURL: 'images/pauls.jpg',
    GroceryItemsList: [Products(
        id: 13,
        title: 'Dry Beans ',
        subtitle: 'Common Pulses',
        amount: '10',
        quantity: 1,
        imageURL: 'images/db.jpeg'),
      Products(
          id: 14,
          title: 'Lentils ',
          subtitle: 'Common Pulses',
          amount: '15',
          quantity: 1,
          imageURL: 'images/l.jpg'),
      Products(
          id: 15,
          title: 'Dry Peas ',
          subtitle: 'Common Pulses',
          amount: '10',
          quantity: 1,
          imageURL: 'images/dp.jpg'),
      Products(
          id: 16,
          title: 'Chickpeas  ',
          subtitle: 'Common Pulses',
          amount: '5',
          quantity: 1,
          imageURL: 'images/c2.jpg'),
      Products(
          id: 17,
          title: 'Cowpeas',
          subtitle: 'Common Pulses',
          amount: '10',
          quantity: 1,
          imageURL: 'images/c3.jpg'),
      Products(
          id: 18,
          title: 'Vetches  ',
          subtitle: 'Common Pulses',
          amount: '10',
          quantity: 1,
          imageURL: 'images/v.jpeg'),]),
    GroceryItems(
        title: 'Rices',
        itemColor: Colors.lightBlueAccent,
        imageURL: 'images/rice.jpeg',
        GroceryItemsList: [Products(
            id: 19,
            title: 'Black Rice ',
            subtitle: 'Rice',
            amount: '10',
            quantity: 1,
            imageURL: 'images/br.jpg'),
          Products(
              id: 20,
              title: 'Basmati Rice',
              subtitle: 'Rice',
              amount: '15',
              quantity: 1,
              imageURL: 'images/bsr.jpg'),
          Products(
              id: 21,
              title: 'Regular Rice',
              subtitle: 'Rice',
              amount: '10',
              quantity: 1,
              imageURL: 'images/nr.png'),
          Products(
              id: 22,
              title: 'India Gate',
              subtitle: 'Rice',
              amount: '5',
              quantity: 1,
              imageURL: 'images/ir.jpeg'),
          Products(
              id: 23,
              title: 'Daawat Regular',
              subtitle: 'Rice',
              amount: '10',
              quantity: 1,
              imageURL: 'images/droj.jpg'),
          Products(
              id: 24,
              title: 'Kohinoor',
              subtitle: 'Rice',
              amount: '10',
              quantity: 1,
              imageURL: 'images/k.jpeg'),]),
    GroceryItems(
        title: 'Fruits',
        itemColor: Colors.yellow.shade400,
        imageURL: 'images/fruit.jpg',GroceryItemsList: [ Products(
        id: 1,
        title: 'Apple',
        subtitle: 'Fruit',
        amount: '1.3',
        quantity: 1,
        imageURL: 'images/a.jpg'),
      Products(
          id: 2,
          title: 'Banana',
          subtitle: 'Fruits',
          amount: '1.0',
          quantity: 1,
          imageURL: 'images/b.jpg'),
      Products(
          id: 3,
          title: 'Grapes',
          subtitle: 'Fruits',
          amount: '2.0',
          quantity: 1,
          imageURL: 'images/g.jpg'),
      Products(
          id: 4,
          title: 'JackFruits',
          subtitle: 'Fruits',
          amount: '0.5',
          quantity: 1,
          imageURL: 'images/j.jpg'),
      Products(
          id: 5,
          title: 'Blue Berry',
          subtitle: 'Fruits',
          amount: '2.5',
          quantity: 1,
          imageURL: 'images/bb.jpeg'),
      Products(
          id: 6,
          title: 'StrawBerry',
          subtitle: 'Fruits',
          amount: '1.6',
          quantity: 1,
          imageURL: 'images/s.jpg'),]),
    GroceryItems(
        title: 'Oils',
        itemColor: Colors.green.shade300,
        imageURL: 'images/oil.jpg',
        GroceryItemsList: [Products(
            id: 25,
            title: 'Refined Oil',
            subtitle: 'Oils',
            amount: '10',
            quantity: 1,
            imageURL: 'images/co.jpeg'),
          Products(
              id: 26,
              title: 'Mazolla',
              subtitle: 'Oils',
              amount: '15',
              quantity: 1,
              imageURL: 'images/ol.jpeg'),
          Products(
              id: 27,
              title: 'Oliv Oil',
              subtitle: 'Oils',
              amount: '10',
              quantity: 1,
              imageURL: 'images/ooil.webp'),
          Products(
              id: 28,
              title: 'Avocardo Oil',
              subtitle: 'Oils',
              amount: '5',
              quantity: 1,
              imageURL: 'images/avooil.jpeg'),
          Products(
              id: 29,
              title: 'Sunflower Oil',
              subtitle: 'Oils',
              amount: '10',
              quantity: 1,
              imageURL: 'images/sunoil.webp'),
          Products(
              id: 30,
              title: 'Organic Oil',
              subtitle: 'Common Pulses',
              amount: '10',
              quantity: 1,
              imageURL: 'images/voil.jpg'),]),
    GroceryItems(
        title: 'Jams & Honey',
        itemColor: Colors.red.shade200,
        imageURL: 'images/jams.jpg',GroceryItemsList: [Products(
        id: 31,
        title: 'Strawberry Jam',
        subtitle: 'Jams',
        amount: '10',
        quantity: 1,
        imageURL: 'images/j.jpeg'),
      Products(
          id: 32,
          title: 'Mix Fruit Jam',
          subtitle: 'Common Pulses',
          amount: '15',
          quantity: 1,
          imageURL: 'images/mj.webp'),
      Products(
          id: 33,
          title: 'Dry Peas ',
          subtitle: 'Common Pulses',
          amount: '10',
          quantity: 1,
          imageURL: 'images/dp.jpg'),
      Products(
          id: 34,
          title: 'Chickpeas  ',
          subtitle: 'Common Pulses',
          amount: '5',
          quantity: 1,
          imageURL: 'images/c2.jpg'),
      Products(
          id: 35,
          title: 'Cowpeas',
          subtitle: 'Common Pulses',
          amount: '10',
          quantity: 1,
          imageURL: 'images/c3.jpg'),
      Products(
          id: 35,
          title: 'Vetches  ',
          subtitle: 'Common Pulses',
          amount: '10',
          quantity: 1,
          imageURL: 'images/v.jpeg'),]),
    GroceryItems(
        title: 'Chocolate',
        itemColor: Colors.indigoAccent.shade200,
        imageURL: 'images/chocolate.jpeg',GroceryItemsList: [Products(
        id:39,
        title: 'Dry Beans ',
        subtitle: 'Common Pulses',
        amount: '10',
        quantity: 1,
        imageURL: 'images/db.jpeg'),
      Products(
          id: 40,
          title: 'Lentils ',
          subtitle: 'Common Pulses',
          amount: '15',
          quantity: 1,
          imageURL: 'images/l.jpg'),
      Products(
          id: 41,
          title: 'Dry Peas ',
          subtitle: 'Common Pulses',
          amount: '10',
          quantity: 1,
          imageURL: 'images/dp.jpg'),
      Products(
          id: 42,
          title: 'Chickpeas  ',
          subtitle: 'Common Pulses',
          amount: '5',
          quantity: 1,
          imageURL: 'images/c2.jpg'),
      Products(
          id: 43,
          title: 'Cowpeas',
          subtitle: 'Common Pulses',
          amount: '10',
          quantity: 1,
          imageURL: 'images/c3.jpg'),
      Products(
          id: 44,
          title: 'Vetches  ',
          subtitle: 'Common Pulses',
          amount: '10',
          quantity: 1,
          imageURL: 'images/v.jpeg'),]),
    GroceryItems(
        title: 'Biscuits',
        itemColor: Colors.tealAccent.shade200,
        imageURL: 'images/biskuts.png',GroceryItemsList: [Products(
        id: 45,
        title: 'Dry Beans ',
        subtitle: 'Common Pulses',
        amount: '10',
        quantity: 1,
        imageURL: 'images/db.jpeg'),
      Products(
          id: 46,
          title: 'Lentils ',
          subtitle: 'Common Pulses',
          amount: '15',
          quantity: 1,
          imageURL: 'images/l.jpg'),
      Products(
          id: 15,
          title: 'Dry Peas ',
          subtitle: 'Common Pulses',
          amount: '10',
          quantity: 1,
          imageURL: 'images/dp.jpg'),
      Products(
          id: 16,
          title: 'Chickpeas  ',
          subtitle: 'Common Pulses',
          amount: '5',
          quantity: 1,
          imageURL: 'images/c2.jpg'),
      Products(
          id: 47,
          title: 'Cowpeas',
          subtitle: 'Common Pulses',
          amount: '10',
          quantity: 1,
          imageURL: 'images/c3.jpg'),
      Products(
          id: 48,
          title: 'Vetches  ',
          subtitle: 'Common Pulses',
          amount: '10',
          quantity: 1,
          imageURL: 'images/v.jpeg'),]),
    GroceryItems(
        title: 'Snacks',
        itemColor: Colors.deepOrangeAccent.shade200,
        imageURL: 'images/snacks.jpg',GroceryItemsList: [Products(
        id: 49,
        title: 'Dry Beans ',
        subtitle: 'Common Pulses',
        amount: '10',
        quantity: 1,
        imageURL: 'images/db.jpeg'),
      Products(
          id: 50,
          title: 'Lentils ',
          subtitle: 'Common Pulses',
          amount: '15',
          quantity: 1,
          imageURL: 'images/l.jpg'),
      Products(
          id: 51,
          title: 'Dry Peas ',
          subtitle: 'Common Pulses',
          amount: '10',
          quantity: 1,
          imageURL: 'images/dp.jpg'),
      Products(
          id: 51,
          title: 'Chickpeas  ',
          subtitle: 'Common Pulses',
          amount: '5',
          quantity: 1,
          imageURL: 'images/c2.jpg'),
      Products(
          id: 53,
          title: 'Cowpeas',
          subtitle: 'Common Pulses',
          amount: '10',
          quantity: 1,
          imageURL: 'images/c3.jpg'),
      Products(
          id: 54,
          title: 'Vetches  ',
          subtitle: 'Common Pulses',
          amount: '10',
          quantity: 1,
          imageURL: 'images/v.jpeg'),]),
    GroceryItems(
        title: 'Eggs',
        itemColor: Colors.purple.shade300,
        imageURL: 'images/eggs.jpg',GroceryItemsList: [Products(
        id: 55,
        title: 'Dry Beans ',
        subtitle: 'Common Pulses',
        amount: '10',
        quantity: 1,
        imageURL: 'images/db.jpeg'),
      Products(
          id: 56,
          title: 'Lentils ',
          subtitle: 'Common Pulses',
          amount: '15',
          quantity: 1,
          imageURL: 'images/l.jpg'),
      Products(
          id: 57,
          title: 'Dry Peas ',
          subtitle: 'Common Pulses',
          amount: '10',
          quantity: 1,
          imageURL: 'images/dp.jpg'),
      Products(
          id: 58,
          title: 'Chickpeas  ',
          subtitle: 'Common Pulses',
          amount: '5',
          quantity: 1,
          imageURL: 'images/c2.jpg'),
      Products(
          id: 59,
          title: 'Cowpeas',
          subtitle: 'Common Pulses',
          amount: '10',
          quantity: 1,
          imageURL: 'images/c3.jpg'),
      Products(
          id: 60,
          title: 'Vetches  ',
          subtitle: 'Common Pulses',
          amount: '10',
          quantity: 1,
          imageURL: 'images/v.jpeg'),]),
    GroceryItems(
        title: 'Mashrooms',
        itemColor: Colors.lightGreenAccent,
        imageURL: 'images/mashrooms.jpg',GroceryItemsList: [Products(
        id: 61,
        title: 'Dry Beans ',
        subtitle: 'Common Pulses',
        amount: '10',
        quantity: 1,
        imageURL: 'images/db.jpeg'),
      Products(
          id: 62,
          title: 'Lentils ',
          subtitle: 'Common Pulses',
          amount: '15',
          quantity: 1,
          imageURL: 'images/l.jpg'),
      Products(
          id: 63,
          title: 'Dry Peas ',
          subtitle: 'Common Pulses',
          amount: '10',
          quantity: 1,
          imageURL: 'images/dp.jpg'),
      Products(
          id: 64,
          title: 'Chickpeas  ',
          subtitle: 'Common Pulses',
          amount: '5',
          quantity: 1,
          imageURL: 'images/c2.jpg'),
      Products(
          id: 65,
          title: 'Cowpeas',
          subtitle: 'Common Pulses',
          amount: '10',
          quantity: 1,
          imageURL: 'images/c3.jpg'),
      Products(
          id: 66,
          title: 'Vetches  ',
          subtitle: 'Common Pulses',
          amount: '10',
          quantity: 1,
          imageURL: 'images/v.jpeg'),]),
  ];

  List<ExploreItems> itemList = [
    ExploreItems(
        title: 'Fruits & vegetables',
        itemColor: Colors.greenAccent.shade400,
        imageURL: 'images/fv.png',
        ItemBackground: Colors.greenAccent.shade100,
        ExploreItemList: [ Products(
            id: 7,
            title: 'Pepsi',
            subtitle: 'Fruit',
            amount: '25',
            quantity: 1,
            imageURL: 'images/p.jpg'),
          Products(
              id: 8,
              title: 'Coco-Cola',
              subtitle: 'Fruits',
              amount: '25',
              quantity: 1,
              imageURL: 'images/c.jpg'),
          Products(
              id: 9,
              title: 'Amul Butter',
              subtitle: 'Fruits',
              amount: '30',
              quantity: 1,
              imageURL: 'images/ab.png'),
          Products(
              id: 10,
              title: 'Horlicks',
              subtitle: 'Fruits',
              amount: '50',
              quantity: 1,
              imageURL: 'images/h.jpeg'),
          Products(
              id: 11,
              title: 'Blue Berry',
              subtitle: 'Fruits',
              amount: '2.5',
              quantity: 1,
              imageURL: 'images/bb.jpeg'),
          Products(
              id: 12,
              title: 'Oliv Oli',
              subtitle: 'Fruits',
              amount: '59',
              quantity: 1,
              imageURL: 'images/o.jpeg'),
        ]),
    ExploreItems(
        title: 'Cooking Oils & Ghee',
        itemColor: Colors.deepOrange.shade400,
        imageURL: 'images/og.png',
        ItemBackground: Colors.deepOrange.shade100,
        ExploreItemList: [Products(
            id: 7,
            title: 'Pepsi',
            subtitle: 'Fruit',
            amount: '25',
            quantity: 1,
            imageURL: 'images/p.jpg'),
          Products(
              id: 8,
              title: 'Coco-Cola',
              subtitle: 'Fruits',
              amount: '25',
              quantity: 1,
              imageURL: 'images/c.jpg'),
          Products(
              id: 9,
              title: 'Amul Butter',
              subtitle: 'Fruits',
              amount: '30',
              quantity: 1,
              imageURL: 'images/ab.png'),
          Products(
              id: 10,
              title: 'Horlicks',
              subtitle: 'Fruits',
              amount: '50',
              quantity: 1,
              imageURL: 'images/h.jpeg'),
          Products(
              id: 11,
              title: 'Blue Berry',
              subtitle: 'Fruits',
              amount: '2.5',
              quantity: 1,
              imageURL: 'images/bb.jpeg'),
          Products(
              id: 12,
              title: 'Oliv Oli',
              subtitle: 'Fruits',
              amount: '59',
              quantity: 1,
              imageURL: 'images/o.jpeg'),
        ]),
    ExploreItems(
        title: 'Meat & Fish',
        itemColor: Colors.pinkAccent,
        imageURL: 'images/mf.webp',
        ItemBackground: Colors.pinkAccent.shade100,
        ExploreItemList: [Products(
  id: 7,
  title: 'Pepsi',
  subtitle: 'Fruit',
  amount: '25',
  quantity: 1,
  imageURL: 'images/p.jpg'),
  Products(
  id: 8,
  title: 'Coco-Cola',
  subtitle: 'Fruits',
  amount: '25',
  quantity: 1,
  imageURL: 'images/c.jpg'),
  Products(
  id: 9,
  title: 'Amul Butter',
  subtitle: 'Fruits',
  amount: '30',
  quantity: 1,
  imageURL: 'images/ab.png'),
  Products(
  id: 10,
  title: 'Horlicks',
  subtitle: 'Fruits',
  amount: '50',
  quantity: 1,
  imageURL: 'images/h.jpeg'),
  Products(
  id: 11,
  title: 'Blue Berry',
  subtitle: 'Fruits',
  amount: '2.5',
  quantity: 1,
  imageURL: 'images/bb.jpeg'),
  Products(
  id: 12,
  title: 'Oliv Oli',
  subtitle: 'Fruits',
  amount: '59',
  quantity: 1,
  imageURL: 'images/o.jpeg'),
        ]),
    ExploreItems(
        title: 'Bakery & Snacks',
        itemColor: Colors.purple,
        imageURL: 'images/bs.png',
        ItemBackground: Colors.purple.shade100,
        ExploreItemList: [Products(
            id: 7,
            title: 'Pepsi',
            subtitle: 'Fruit',
            amount: '25',
            quantity: 1,
            imageURL: 'images/p.jpg'),
          Products(
              id: 8,
              title: 'Coco-Cola',
              subtitle: 'Fruits',
              amount: '25',
              quantity: 1,
              imageURL: 'images/c.jpg'),
          Products(
              id: 9,
              title: 'Amul Butter',
              subtitle: 'Fruits',
              amount: '30',
              quantity: 1,
              imageURL: 'images/ab.png'),
          Products(
              id: 10,
              title: 'Horlicks',
              subtitle: 'Fruits',
              amount: '50',
              quantity: 1,
              imageURL: 'images/h.jpeg'),
          Products(
              id: 11,
              title: 'Blue Berry',
              subtitle: 'Fruits',
              amount: '2.5',
              quantity: 1,
              imageURL: 'images/bb.jpeg'),
          Products(
              id: 12,
              title: 'Oliv Oli',
              subtitle: 'Fruits',
              amount: '59',
              quantity: 1,
              imageURL: 'images/o.jpeg'),
        ]),
    ExploreItems(
        title: 'Dairy & Eggs',
        itemColor: Colors.yellow,
        imageURL: 'images/de.webp',
        ItemBackground: Colors.yellow.shade100,
        ExploreItemList: [ Products(
            id: 7,
            title: 'Pepsi',
            subtitle: 'Fruit',
            amount: '25',
            quantity: 1,
            imageURL: 'images/p.jpg'),
          Products(
              id: 8,
              title: 'Coco-Cola',
              subtitle: 'Fruits',
              amount: '25',
              quantity: 1,
              imageURL: 'images/c.jpg'),
          Products(
              id: 9,
              title: 'Amul Butter',
              subtitle: 'Fruits',
              amount: '30',
              quantity: 1,
              imageURL: 'images/ab.png'),
          Products(
              id: 10,
              title: 'Horlicks',
              subtitle: 'Fruits',
              amount: '50',
              quantity: 1,
              imageURL: 'images/h.jpeg'),
          Products(
              id: 11,
              title: 'Blue Berry',
              subtitle: 'Fruits',
              amount: '2.5',
              quantity: 1,
              imageURL: 'images/bb.jpeg'),
          Products(
              id: 12,
              title: 'Oliv Oli',
              subtitle: 'Fruits',
              amount: '59',
              quantity: 1,
              imageURL: 'images/o.jpeg'),
        ]),
  ];
  final List<IconData> icondata = [
    Icons.shopping_bag_outlined,
    Icons.library_books_outlined,
    Icons.location_on_outlined,
    Icons.payment,
    Icons.local_play_outlined,
    Icons.notification_important_outlined,
    Icons.help_outline_outlined,
    Icons.info_outline
  ];
  final List<String> title = <String>[
    'Orders',
    'My Details',
    'Delivery Address',
    'Payment Methods',
    'Promo Code',
    'Notification',
    'Help',
    'About'
  ];

final List<String> images = <String>[
  'images/picforbanner.jpg',
  'images/picforbanner1.jpg',
  'images/picforbanner2.jpg',
];